In [1]:
# Import libraries
import pandas as pd
from sodapy import Socrata

In [3]:
client = Socrata("data.novascotia.ca", 'cx4XloH6tDgX8ZhFFmtAuxtMc')

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [4]:
# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("eb3n-uxcb", limit=6000000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

In [5]:
results_df

,waterbody,station,lease,latitude,longitude,deployment_period,timestamp,sensor,depth,variable,value
0,Country Harbour,1307,1307,45.16005,-61.68007,2018-Dec-20 to 2019-Apr-02,2018-12-22T21:00:00.000,HOBO-10817410,2,Temperature,3.036
1,Country Harbour,1307,1307,45.16005,-61.68007,2018-Dec-20 to 2019-Apr-02,2018-12-22T22:00:00.000,HOBO-10817410,2,Temperature,3.063
2,Country Harbour,1307,1307,45.16005,-61.68007,2018-Dec-20 to 2019-Apr-02,2018-12-22T23:00:00.000,HOBO-10817410,2,Temperature,3.116
3,Country Harbour,1307,1307,45.16005,-61.68007,2018-Dec-20 to 2019-Apr-02,2018-12-23T00:00:00.000,HOBO-10817410,2,Temperature,3.116
4,Country Harbour,1307,1307,45.16005,-61.68007,2018-Dec-20 to 2019-Apr-02,2018-12-23T01:00:00.000,HOBO-10817410,2,Temperature,3.168
...,...,...,...,...,...,...,...,...,...,...,...
5476950,Chedabucto Bay,Tickle Island,NA,45.3594,-61.04287,2020-Feb-24 to 2020-Oct-21,2020-10-21T08:00:00.000,VR2AR-547232,75,Temperature,3.2
5476951,Chedabucto Bay,Tickle Island,NA,45.3594,-61.04287,2020-Feb-24 to 2020-Oct-21,2020-10-21T09:00:00.000,VR2AR-547232,75,Temperature,3.1
5476952,Chedabucto Bay,Tickle Island,NA,45.3594,-61.04287,2020-Feb-24 to 2020-Oct-21,2020-10-21T10:00:00.000,VR2AR-547232,75,Temperature,3
5476953,Chedabucto Bay,Tickle Island,NA,45.3594,-61.04287,2020-Feb-24 to 2020-Oct-21,2020-10-21T11:00:00.000,VR2AR-547232,75,Temperature,3
5476954,Chedabucto Bay,Tickle Island,NA,45.3594,-61.04287,2020-Feb-24 to 2020-Oct-21,2020-10-21T12:00:00.000,VR2AR-547232,75,Temperature,7.2

In [23]:
subset_df = results_df.iloc[0:2000]
subset_df.loc[:, ('timestamp')] = pd.to_datetime(subset_df['timestamp'])
# typed_subset_df = subset_df.infer_objects()

In [27]:
grouped_df = subset_df.groupby(['waterbody', 'station', 'lease', 'latitude', 'longitude', 'deployment_period', 'timestamp', 'sensor', 'depth'])

In [41]:
def custom_agg_function(group):
    new_df = pd.DataFrame()
    print(dataframe['variable'])
    print(dataframe['value'])
    print('========*****=========')
    print(dataframe.dtypes)
    print('========*****=========')
    raise('stop')

In [42]:
grouped_df.apply(custom_agg_function)

0    Temperature
Name: variable, dtype: object
0    3.036
Name: value, dtype: object
========*****=========
waterbody                    object
station                      object
lease                        object
latitude                     object
longitude                    object
deployment_period            object
timestamp            datetime64[ns]
sensor                       object
depth                        object
variable                     object
value                        object
dtype: object
========*****=========
0    Temperature
Name: variable, dtype: object
0    3.036
Name: value, dtype: object
========*****=========
waterbody                    object
station                      object
lease                        object
latitude                     object
longitude                    object
deployment_period            object
timestamp            datetime64[ns]
sensor                       object
depth                        object
variable                     object
value                        object
dtype: object
========*****=========
0    Temperature
Name: variable, dtype: object
0    3.036
Name: value, dtype: object
========*****=========
variable    object
value       object
dtype: object
========*****=========
0    Temperature
Name: variable, dtype: object
0    3.036
Name: value, dtype: object
========*****=========
variable    object
value       object
dtype: object
========*****=========

TypeError: exceptions must derive from BaseException